baseURL = 'https://www.nicecode.app/'
languageCode = 'ja-jp'
title = 'NiceCode'
theme = ["hugo-initio"]

[params]
    name = "NiceCode"
    description = "池袋・板橋を中心としたシステムエンジニアリング企業です"
    email = "kotetsu@nicecode.app"
    phone = ""
    address = ""
    year = 2022
    avatar = "images/logo.png"
    avatarclass = "square"
    background = ""
    banner = "images/bg_head.jpg"
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

#[[menu.main]]
#    name = "home"
#    url = "/"
#    weight = 1

#[[menu.main]]
#    name = "blog"
#    url = "/post/"
#    weight = 5

#[params.disqus]
#    site = "hugo-initio-site.disqus.com"

#[params.sharethis]
#    property = "123456789012345678901234"
#    custom = true

#[params.google.analytics]
#    trackerID = "GA-000000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/tety"
    icon = "fab fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/kotetsu"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
    title = "github"
    url = "https://github.com/t-kobayashi"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
    title = "email"
    url = "mailto:kotetsu@nicecode.app"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
